### ISSUE TITLE
PDF documents not using same fonts as SI Brochure

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-bipm#35]
Need to use the same GHA flow as bipm-si-brochure repo.

**Comment by CAMOBAP** [comment]
@ronaldtse we need to prepare a similar manifest as `bipm-si-brochure` have  https://github.com/metanorma/bipm-si-brochure/blob/master/si-brochure-bilingual.yml for this repo

I'm not sure which docs need to be added to it

**Comment by ronaldtse** [comment]
@CAMOBAP we already have all docs in the metanorma.UML here, just need to make sure that the fonts are installed. Thanks.

**Comment by CAMOBAP** [comment]
@ronaldtse the only difference between this repo and `bipm-si-brochure` is that `bipm-si-brochure` contains an extra `metanorma collection...` step

There is nothing font specific in GHA of `bipm-si-brochure` repo.

AFAIK all fonts are hardcoded in our `metanorma-*` repos (hardcoded manifest in ruby code)

I have checked the last CI run https://github.com/metanorma/mn-samples-bipm/runs/3959094548?check_suite_focus=true
Probably I missing something, because I don't understand how we can fix missing font issue on mn-samples-bipm level

**Comment by ronaldtse** [comment]
Thanks! It's all working now. The font usage can be verified on the deployed GitHub Pages.
